name: 'Check commit status'
inputs:
  statusName:
    description: 'Name of the commit status to check'
    required: true
  testVaL:
    description: 'Test value'

runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo "statusName: ${{ inputs.statusName }}"
        echo "testVaL: ${{ inputs.testVaL }}"
