apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretbindings.core.gardener.cloud
spec:
  group: core.gardener.cloud
  names:
    kind: SecretBinding
    plural: secretbindings
    singular: secretbinding
    shortNames:
      - sb
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum:
                - core.gardener.cloud/v1beta1
            kind:
              type: string
              enum:
                - SecretBinding
            metadata:
              type: object
            provider:
              type: object
              properties:
                type:
                  type: string
            secretRef:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
          required:
            - apiVersion
            - kind
            - metadata
            - provider
            - secretRef
