apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shoots.core.gardener.cloud
spec:
  group: core.gardener.cloud
  names:
    kind: Shoot
    plural: shoots
    singular: shoot
    shortNames:
      - sh
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                addons:
                  type: object
                cloudProfileName:
                  type: string
                dns:
                  type: object
                extensions:
                  type: array
                  items:
                    type: object
                hibernation:
                  type: object
                kubernetes:
                  type: object
                networking:
                  type: object
                maintenance:
                  type: object
                monitoring:
                  type: object
                provider:
                  type: object
                purpose:
                  type: string
                region:
                  type: string
                secretBindingName:
                  type: string
                seedName:
                  type: string
                seedSelector:
                  type: object
                resources:
                  type: array
                  items:
                    type: object
                tolerations:
                  type: array
                  items:
                    type: object
                exposureClassName:
                  type: string
                systemComponents:
                  type: object
                controlPlane:
                  type: object
                schedulerName:
                  type: string
                cloudProfile:
                  type: object
                credentialsBindingName:
                  type: string
                accessRestrictions:
                  type: array
                  items:
                    type: object
            status:
              type: object
      subresources:
        status: {}
