name: Enable auto merge
on:
  pull_request_target:
    branches: [main]
    types:
    - opened
    - reopened
    - ready_for_review
    - synchronize

permissions:
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.BOT_TOKEN}}
          GIT_EMAIL: team-gopher+1@sap.com
        run: gh pr merge -A ${{ env.GIT_EMAIL }} --auto --squash "$PR_URL"
