name: "Create PR"


on:
  workflow_dispatch:


jobs:
  validate-release:
    name: Validate release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Create a random file
          run: echo "This is a dummy file" > $(uuidgen).txt
  
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
  
