name: "Create release"
run-name: Create release ${{ inputs.name }}

env:
  IMAGE_REPO: europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker
  KYMA_ENVIRONMENT_BROKER_REPO: ${{ github.repository_owner }}/kyma-environment-broker
  GIT_EMAIL: team-gopher+1@sap.com
  GIT_NAME: kyma-gopher-bot
  BUMP_CHART_AND_IMAGES: bump-chart-and-images-${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Create release'
        default: ""
        required: true
      dry-run:
        type: boolean
        description: 'Do not publish'
        default: false

jobs:
  label-prs:
    name: Label PRs with do-not-merge/release-in-progress
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add do-not-merge/release-in-progress label to all opened PR's
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          open_prs=$(gh pr list --state open --json number --jq '.[].number')
          for pr in $open_prs; do
              gh pr edit $pr --add-label do-not-merge/release-in-progress
          done

  validate-release:
    name: Validate release
    needs: label-prs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag already exists
        run: |
          if [ $(git tag -l ${{ inputs.name }}) ]; then
            echo "::error ::Tag ${{ inputs.name }} already exists"
            exit 1
          fi

      - name: Check for existing artifacts from previous release runs
        run: "./scripts/check_artifacts_existence.sh ${{ inputs.name }}"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r scripts/python/requirements.txt

      - name: Validate labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ env.KYMA_ENVIRONMENT_BROKER_REPO }}
          NAME: ${{ inputs.name }}
        run: python3 scripts/python/release_label_validator.py

  run-unit-tests:
    name: Unit tests, go mod tidy
    needs: label-prs
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"

  unlabel-prs:
    name: Unlabel PRs with do-not-merge/release-in-progress
    needs: [run-unit-tests, validate-release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Remove do-not-merge/release-in-progress labels from opened PR's
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          open_prs=$(gh pr list --state open --json number --jq '.[].number')
          for pr in $open_prs; do
              gh pr edit $pr --remove-label do-not-merge/release-in-progress
          done

 # check-release-in-progress:
  #  name: Check if another release is in progress
   # runs-on: ubuntu-latest
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v4
       # with:
        #  fetch-depth: 0

#      - name: Check for release in progress
 #       env:
  #        GH_TOKEN: ${{ secrets.BOT_TOKEN }}
   #     run: |
    #      in_progress=$(gh run list --workflow="Create release" --status="in_progress" --json name --jq '.[].name')
     #     if [ -n "$in_progress" ]; then
      #      echo "::error ::Another release is already in progress: $in_progress"
       #     exit 1
        #  fi