name: All checks passed
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    - edited
    - labeled
    - unlabeled
  pull_request_review:
    types:
    - submitted
    - edited
      
jobs:
  checks-passed:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - name: Check if draft
        if: ${{ github.event.pull_request.draft }}
        run: | 
          echo "Draft PRs are not checked"
          exit 1
      - name: Check if author is kyma-gopher-bot
        if: ${{ github.event.pull_request.user.login == 'kyma-gopher-bot' }}
        run: | 
          echo "PRs from kyma-gopher-bot are automatically green"
          exit 0
      - name: Check if create-release workflow is in progress
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Checking if create-release workflow is in progress"
          in_progress_workflows=$(gh run list --workflow="Create release" --status="in_progress" --json name --jq '.[].name')
          if [ -n "$in_progress_workflows" ]; then
            echo "Create release workflow is in progress"
            exit 1
          fi
      - uses: wechuli/allcheckspassed@2e5e8bbc775f5680ed5d02e3a22e2fc7219792ac
        if: ${{ github.event.pull_request.user.login != 'kyma-gopher-bot' }}
        with:
          delay: '1'
          retries: '15'
          polling_interval: '1'
          checks_exclude: 'markdown-link-check,enable-auto-merge,run-govulncheck,scan'
          verbose: true
