name: Verify KEB

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  run-go-tests:
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"

  run-go-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Check changes
      run: |
        curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MarekMichali/kyma-environment-broker/pulls/${{ github.event.pull_request.number }}/files | jq -r '.[].filename'

    - name: Set up go environment
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        
    - name: Go linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
        skip-cache: true
        only-new-issues: true
        args: --timeout 2m0s

  run-go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run go checks
        run: make checks