# Call this workflow from other jobs to execute helm template in the current context

name: Run helm template (reusable)

on:
  workflow_call:
    inputs:
      last-k3s-versions:
        description: number of the most recent K3s versions to be used
        required: false
        default: 1
        type: string

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run helm template
      run: |
        cd resources/keb
        helm template .
  
  prepare-tests:
    runs-on: ubuntu-latest
    needs: helm-template
    outputs:
      versions: ${{ steps.get-versions.outputs.k3s_versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: get-versions
        name: Get K3s versions
        # prepare json representing GitHub matrix:
        # {"include": [
        #    {"version":"v1.26.10+k3s1"},
        #      ...
        #    {"version":"v1.28.3+k3s1"}
        # ]
        # }
        run: |
          VERSIONS=($(./scripts/testing/get-latest-k3s-releases.sh ${{ inputs.last-k3s-versions }}))
          MATRIX_AS_JSON=$(echo ${VERSIONS[*]} | awk 'END {printf "{\"include\":[";for (i = 1; i < NF; i++) printf "{\"version\":%s},",$i;printf "{\"version\":%s}]}",$i }'|jq -c)
          echo "k3s_versions=${MATRIX_AS_JSON}" >> "${GITHUB_OUTPUT}"

  run-e2e-matrix:
    runs-on: ubuntu-latest
    needs: prepare-tests
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare K3s cluster and docker registry
        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"

      - name: Create namespaces
        run: |
          kubectl create namespace kcp-system
          kubectl create namespace kyma-system
          kubectl create namespace istio-system

      - name: Install istio
        run: |
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm install istio-base istio/base -n istio-system --set defaultRevision=default

      - name: Apply helm chart
        run: |
          cd resources/keb
          helm template . | kubectl apply -f -
  
  check-e2e-status:
    needs: run-e2e-matrix
    runs-on: ubuntu-latest
    if: success() 
    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
      - id: setoutput
        run: echo "::set-output name=success::true"

  finish-e2e-tests:
    runs-on: ubuntu-latest
    if: always()
    needs: [run-e2e-matrix, check-e2e-status]
    steps:
      - name: Final step
        run: |
          passed="${{ needs.check-e2e-status.outputs.success }}"
          if [[ $passed == "true" ]]; then
            echo "Shards passed"
            exit 0
          else
            echo "Shards failed"
            exit 1
          fi