name: Run JS linter

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "sec-scanners-config.yaml"
      - "**.go"
    
jobs:
  run-eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run JS linter
      run: make lint -C testing/e2e/skr
