# Call this workflow from other jobs to execute unit tests in the current context

name: Run unit tests (reusable)
on:
  workflow_call:
    inputs:
      release:
        type: boolean
        description: 'Determines if the workflow is called from release'
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v42
      with:
        files: |
          cmd/**
          common/**
          files/**
          internal/**
          scripts/**
          utils/**
          .golangci.yml
          Dockerfile.job
          Dockerfile.keb
          Dockerfile.runtimereconciler
          go.mod
          go.sum
          Makefile

    - name: Set up go environment
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' ||  inputs.release == 'true' }}
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Run unit tests
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' ||  inputs.release == 'true' }}
      run: make test