name: Run helm template

on:
  push:
    branches: [ "main" ]
  pull_request:
    # Trigger for Pull Request
    branches: [ "main" ]

jobs:
  run-unit-tests:
    uses: "./.github/workflows/run-helm-template-reusable.yaml"
