name: Verify KEB

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.md"
      - "sec-scanners-config.yaml"
  
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  run-go-tests:
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"

  run-go-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up go environment
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        
    - name: Go linter
      env:
        GOLINT_TIMEOUT: ${{ vars.GOLINT_TIMEOUT }}
      run: make go-lint

  run-go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run go checks
        run: make checks

  verify-python-md-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r scripts/python/requirements.txt

      - name: Run env docs generator
        run: python3 scripts/python/generate_env_docs.py

      - name: Check for changes in docs/contributor/02-30-keb-configuration.md
        run: |
          if [[ $(git status --porcelain docs/contributor/02-30-keb-configuration.md) ]]; then
            echo 'docs/contributor/02-30-keb-configuration.md is out of date. Please run the generator and commit the changes.'
            git diff docs/contributor/02-30-keb-configuration.md
            exit 1
          fi