name: Validate KEB chart

on:
  workflow_run:
    workflows: ["pull-build-images-ga"]
    types:
      - completed
jobs:
  run-keb-chart-tests:
    uses: "./.github/workflows/run-keb-chart-install-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.draft }}
    with:
      last-k3s-versions: 3
      release: "false"

