apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    hyperscalerType: aws
  name: aws-secret-binding
  namespace: garden-kyma-dev
provider:
  type: aws
secretRef:
  name: aws-secret
  namespace: garden-kyma-dev
