apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    hyperscalerType: azure
  name: azure-secret-binding
  namespace: garden-kyma-dev
provider:
  type: azure
secretRef:
  name: azure-secret
  namespace: garden-kyma-dev
